

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Solicitud_Estados_AdministrativoItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad Solicitud_Estados_AdministrativoItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Solicitud_Estados_AdministrativoItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Solicitud_Estados_AdministrativoItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Solicitud_Estados_AdministrativoItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Solicitud_Estados_AdministrativoItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id_Estados_Administrativo
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Id_Estados_Administrativo);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Estados_Administrativo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Estados_Administrativo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Estados_Administrativo_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Observaciones
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Observaciones);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Observaciones, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Observaciones_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Observaciones_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Observaciones_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TituloObservacion
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.TituloObservacion);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.TituloObservacion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TituloObservacion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TituloObservacion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TituloObservacion_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MensajeBy
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.MensajeBy);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.MensajeBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MensajeBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MensajeBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MensajeBy_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreadoAt
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.CreadoAt);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.CreadoAt, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreadoAt_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreadoAt_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreadoAt_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem Solicitud_Detalle_AdministrativoItem
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Solicitud_Detalle_AdministrativoItem);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Solicitud_Detalle_AdministrativoItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Solicitud_Detalle_AdministrativoItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Solicitud_Detalle_AdministrativoItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Solicitud_Detalle_AdministrativoItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem,
                global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass,
                global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Id_Estados_Administrativo;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass>.Entry
                __Solicitud_Estados_AdministrativoItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.__Solicitud_Estados_AdministrativoItem_CreateNew,
                    global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.__Solicitud_Estados_AdministrativoItem_Created,
                    global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.__Solicitud_Estados_AdministrativoItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem __Solicitud_Estados_AdministrativoItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem> es)
            {
                return new global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem(es);
            }
            private static void __Solicitud_Estados_AdministrativoItem_Created(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
            {
                e.Solicitud_Estados_AdministrativoItem_Created();
            }
            private static bool __Solicitud_Estados_AdministrativoItem_AllowSaveWithErrors(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
            {
                bool result = false;
                e.Solicitud_Estados_AdministrativoItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, int> Id_Estados_Administrativo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Id_Estados_Administrativo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string> Observaciones
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Observaciones) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string> TituloObservacion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.TituloObservacion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string> MensajeBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.MensajeBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::System.Nullable<global::System.DateTime>> CreadoAt
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.CreadoAt) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem> Solicitud_Detalle_AdministrativoItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Solicitud_Detalle_AdministrativoItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id_Estados_Administrativo { get; }
                new string Observaciones { get; set; }
                new string TituloObservacion { get; set; }
                new string MensajeBy { get; set; }
                new global::System.Nullable<global::System.DateTime> CreadoAt { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Solicitud_Detalle_AdministrativoItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, int>.Entry
                    Id_Estados_Administrativo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, int>.Entry(
                        "Id_Estados_Administrativo",
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Id_Estados_Administrativo_Stub,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Id_Estados_Administrativo_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Id_Estados_Administrativo_Validate,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Id_Estados_Administrativo_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Id_Estados_Administrativo_OnValueChanged);
                private static void _Id_Estados_Administrativo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id_Estados_Administrativo, sf);
                }
                private static bool _Id_Estados_Administrativo_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    bool result = false;
                    e.Id_Estados_Administrativo_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Estados_Administrativo_Validate(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Estados_Administrativo_Validate(r);
                }
                private static int _Id_Estados_Administrativo_GetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id_Estados_Administrativo;
                }
                private static void _Id_Estados_Administrativo_OnValueChanged(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    e.Id_Estados_Administrativo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Entry
                    Observaciones = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Entry(
                        "Observaciones",
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Observaciones_Stub,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Observaciones_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Observaciones_Validate,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Observaciones_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Observaciones_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Observaciones_OnValueChanged);
                private static void _Observaciones_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Observaciones, sf);
                }
                private static bool _Observaciones_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    bool result = false;
                    e.Observaciones_IsReadOnly(ref result);
                    return result;
                }
                private static void _Observaciones_Validate(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Observaciones_Validate(r);
                }
                private static string _Observaciones_GetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Observaciones;
                }
                private static void _Observaciones_SetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Observaciones = v;
                }
                private static void _Observaciones_OnValueChanged(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    e.Observaciones_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Entry
                    TituloObservacion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Entry(
                        "TituloObservacion",
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._TituloObservacion_Stub,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._TituloObservacion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._TituloObservacion_Validate,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._TituloObservacion_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._TituloObservacion_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._TituloObservacion_OnValueChanged);
                private static void _TituloObservacion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._TituloObservacion, sf);
                }
                private static bool _TituloObservacion_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    bool result = false;
                    e.TituloObservacion_IsReadOnly(ref result);
                    return result;
                }
                private static void _TituloObservacion_Validate(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TituloObservacion_Validate(r);
                }
                private static string _TituloObservacion_GetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.TituloObservacion;
                }
                private static void _TituloObservacion_SetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.TituloObservacion = v;
                }
                private static void _TituloObservacion_OnValueChanged(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    e.TituloObservacion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Entry
                    MensajeBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Entry(
                        "MensajeBy",
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._MensajeBy_Stub,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._MensajeBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._MensajeBy_Validate,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._MensajeBy_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._MensajeBy_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._MensajeBy_OnValueChanged);
                private static void _MensajeBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MensajeBy, sf);
                }
                private static bool _MensajeBy_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    bool result = false;
                    e.MensajeBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _MensajeBy_Validate(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MensajeBy_Validate(r);
                }
                private static string _MensajeBy_GetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.MensajeBy;
                }
                private static void _MensajeBy_SetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MensajeBy = v;
                }
                private static void _MensajeBy_OnValueChanged(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    e.MensajeBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreadoAt = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreadoAt",
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._CreadoAt_Stub,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._CreadoAt_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._CreadoAt_Validate,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._CreadoAt_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._CreadoAt_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._CreadoAt_OnValueChanged);
                private static void _CreadoAt_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._CreadoAt, sf);
                }
                private static bool _CreadoAt_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    bool result = false;
                    e.CreadoAt_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreadoAt_Validate(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreadoAt_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreadoAt_GetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.CreadoAt;
                }
                private static void _CreadoAt_SetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreadoAt = global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreadoAt_OnValueChanged(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    e.CreadoAt_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem>.Entry
                    Solicitud_Detalle_AdministrativoItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem>.Entry(
                        "Solicitud_Detalle_AdministrativoItem",
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Solicitud_Detalle_AdministrativoItem_Stub,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Solicitud_Detalle_AdministrativoItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Solicitud_Detalle_AdministrativoItem_Validate,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Solicitud_Detalle_AdministrativoItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Solicitud_Detalle_AdministrativoItem_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Solicitud_Detalle_AdministrativoItem_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Solicitud_Detalle_AdministrativoItem_Refresh,
                        global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties._Solicitud_Detalle_AdministrativoItem_OnValueChanged);
                private static void _Solicitud_Detalle_AdministrativoItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem>.Data> c, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Solicitud_Detalle_AdministrativoItem, sf);
                }
                private static bool _Solicitud_Detalle_AdministrativoItem_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    bool result = false;
                    e.Solicitud_Detalle_AdministrativoItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _Solicitud_Detalle_AdministrativoItem_Validate(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Solicitud_Detalle_AdministrativoItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Solicitud_Detalle_AdministrativoItem_GetCoreImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Solicitud_Detalle_AdministrativoItem;
                }
                private static global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem _Solicitud_Detalle_AdministrativoItem_GetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem, global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem.DetailsClass>(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Solicitud_Detalle_AdministrativoItem, ref d._Solicitud_Detalle_AdministrativoItem);
                }
                private static void _Solicitud_Detalle_AdministrativoItem_SetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d, global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Solicitud_Detalle_AdministrativoItem, ref d._Solicitud_Detalle_AdministrativoItem, (i, ev) => i.Solicitud_Detalle_AdministrativoItem = ev, v);
                }
                private static void _Solicitud_Detalle_AdministrativoItem_Refresh(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass.PropertySetProperties.Solicitud_Detalle_AdministrativoItem, ref d._Solicitud_Detalle_AdministrativoItem);
                }
                private static void _Solicitud_Detalle_AdministrativoItem_OnValueChanged(global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem e)
                {
                    e.Solicitud_Detalle_AdministrativoItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, int>.Data _Id_Estados_Administrativo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Data _Observaciones;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Data _TituloObservacion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, string>.Data _MensajeBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreadoAt;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem, global::LightSwitchApplication.Solicitud_Estados_AdministrativoItem.DetailsClass, global::LightSwitchApplication.Solicitud_Detalle_AdministrativoItem>.Data _Solicitud_Detalle_AdministrativoItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
