

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class ConsultarSaldoVacacionesItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad ConsultarSaldoVacacionesItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ConsultarSaldoVacacionesItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ConsultarSaldoVacacionesItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ConsultarSaldoVacacionesItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConsultarSaldoVacacionesItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConsultarSaldoVacacionesItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int id
        {
            get
            {
                return global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.id);
            }
            set
            {
                global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Fecha);
            }
            set
            {
                global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Fecha, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Rut
        {
            get
            {
                return global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Rut);
            }
            set
            {
                global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Rut, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rut_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rut_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rut_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Contrato
        {
            get
            {
                return global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Contrato);
            }
            set
            {
                global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Contrato, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Contrato_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Contrato_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Contrato_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> Saldo
        {
            get
            {
                return global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Saldo);
            }
            set
            {
                global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Saldo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Saldo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Saldo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Saldo_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ConsultarSaldoVacacionesItem,
                global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass,
                global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass>.Entry
                __ConsultarSaldoVacacionesItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.__ConsultarSaldoVacacionesItem_CreateNew,
                    global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.__ConsultarSaldoVacacionesItem_Created,
                    global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.__ConsultarSaldoVacacionesItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ConsultarSaldoVacacionesItem __ConsultarSaldoVacacionesItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ConsultarSaldoVacacionesItem> es)
            {
                return new global::LightSwitchApplication.ConsultarSaldoVacacionesItem(es);
            }
            private static void __ConsultarSaldoVacacionesItem_Created(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
            {
                e.ConsultarSaldoVacacionesItem_Created();
            }
            private static bool __ConsultarSaldoVacacionesItem_AllowSaveWithErrors(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
            {
                bool result = false;
                e.ConsultarSaldoVacacionesItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int> id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.DateTime> Fecha
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Fecha) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, string> Rut
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Rut) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int> Contrato
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Contrato) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.Nullable<double>> Saldo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties.Saldo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int id { get; set; }
                new global::System.DateTime Fecha { get; set; }
                new string Rut { get; set; }
                new int Contrato { get; set; }
                new global::System.Nullable<double> Saldo { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int>.Entry
                    id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int>.Entry(
                        "id",
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._id_Stub,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._id_ComputeIsReadOnly,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._id_Validate,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._id_GetImplementationValue,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._id_SetImplementationValue,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._id_OnValueChanged);
                private static void _id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._id, sf);
                }
                private static bool _id_ComputeIsReadOnly(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
                {
                    bool result = false;
                    e.id_IsReadOnly(ref result);
                    return result;
                }
                private static void _id_Validate(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.id_Validate(r);
                }
                private static int _id_GetImplementationValue(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.id;
                }
                private static void _id_SetImplementationValue(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.id = v;
                }
                private static void _id_OnValueChanged(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
                {
                    e.id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.DateTime>.Entry
                    Fecha = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.DateTime>.Entry(
                        "Fecha",
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Fecha_Stub,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Fecha_ComputeIsReadOnly,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Fecha_Validate,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Fecha_GetImplementationValue,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Fecha_SetImplementationValue,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Fecha_OnValueChanged);
                private static void _Fecha_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Fecha, sf);
                }
                private static bool _Fecha_ComputeIsReadOnly(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
                {
                    bool result = false;
                    e.Fecha_IsReadOnly(ref result);
                    return result;
                }
                private static void _Fecha_Validate(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Fecha_Validate(r);
                }
                private static global::System.DateTime _Fecha_GetImplementationValue(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Fecha;
                }
                private static void _Fecha_SetImplementationValue(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.Fecha = global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.TruncateDate(v);
                }
                private static void _Fecha_OnValueChanged(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
                {
                    e.Fecha_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, string>.Entry
                    Rut = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, string>.Entry(
                        "Rut",
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Rut_Stub,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Rut_ComputeIsReadOnly,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Rut_Validate,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Rut_GetImplementationValue,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Rut_SetImplementationValue,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Rut_OnValueChanged);
                private static void _Rut_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Rut, sf);
                }
                private static bool _Rut_ComputeIsReadOnly(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
                {
                    bool result = false;
                    e.Rut_IsReadOnly(ref result);
                    return result;
                }
                private static void _Rut_Validate(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Rut_Validate(r);
                }
                private static string _Rut_GetImplementationValue(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Rut;
                }
                private static void _Rut_SetImplementationValue(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Rut = v;
                }
                private static void _Rut_OnValueChanged(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
                {
                    e.Rut_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int>.Entry
                    Contrato = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int>.Entry(
                        "Contrato",
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Contrato_Stub,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Contrato_ComputeIsReadOnly,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Contrato_Validate,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Contrato_GetImplementationValue,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Contrato_SetImplementationValue,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Contrato_OnValueChanged);
                private static void _Contrato_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Contrato, sf);
                }
                private static bool _Contrato_ComputeIsReadOnly(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
                {
                    bool result = false;
                    e.Contrato_IsReadOnly(ref result);
                    return result;
                }
                private static void _Contrato_Validate(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Contrato_Validate(r);
                }
                private static int _Contrato_GetImplementationValue(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Contrato;
                }
                private static void _Contrato_SetImplementationValue(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Contrato = v;
                }
                private static void _Contrato_OnValueChanged(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
                {
                    e.Contrato_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.Nullable<double>>.Entry
                    Saldo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.Nullable<double>>.Entry(
                        "Saldo",
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Saldo_Stub,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Saldo_ComputeIsReadOnly,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Saldo_Validate,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Saldo_GetImplementationValue,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Saldo_SetImplementationValue,
                        global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass.PropertySetProperties._Saldo_OnValueChanged);
                private static void _Saldo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Saldo, sf);
                }
                private static bool _Saldo_ComputeIsReadOnly(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
                {
                    bool result = false;
                    e.Saldo_IsReadOnly(ref result);
                    return result;
                }
                private static void _Saldo_Validate(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Saldo_Validate(r);
                }
                private static global::System.Nullable<double> _Saldo_GetImplementationValue(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Saldo;
                }
                private static void _Saldo_SetImplementationValue(global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.Saldo = v;
                }
                private static void _Saldo_OnValueChanged(global::LightSwitchApplication.ConsultarSaldoVacacionesItem e)
                {
                    e.Saldo_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int>.Data _id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.DateTime>.Data _Fecha;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, string>.Data _Rut;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, int>.Data _Contrato;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ConsultarSaldoVacacionesItem, global::LightSwitchApplication.ConsultarSaldoVacacionesItem.DetailsClass, global::System.Nullable<double>>.Data _Saldo;
            
        }
    
        #endregion
    }
    
    #endregion
}
