

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class CorreosDeAvisosItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad CorreosDeAvisosItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CorreosDeAvisosItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CorreosDeAvisosItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CorreosDeAvisosItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CorreosDeAvisosItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CorreosDeAvisosItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int id
        {
            get
            {
                return global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Nombre
        {
            get
            {
                return global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.Nombre);
            }
            set
            {
                global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.Nombre, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nombre_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nombre_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Nombre_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Email
        {
            get
            {
                return global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.Email);
            }
            set
            {
                global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.Email, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Descripcion
        {
            get
            {
                return global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.Descripcion);
            }
            set
            {
                global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.Descripcion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Descripcion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Descripcion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Descripcion_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> RolPrivado
        {
            get
            {
                return global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.RolPrivado);
            }
            set
            {
                global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.RolPrivado, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolPrivado_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolPrivado_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolPrivado_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.CorreosDeAvisosItem,
                global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass,
                global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass>.Entry
                __CorreosDeAvisosItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.__CorreosDeAvisosItem_CreateNew,
                    global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.__CorreosDeAvisosItem_Created,
                    global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.__CorreosDeAvisosItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.CorreosDeAvisosItem __CorreosDeAvisosItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CorreosDeAvisosItem> es)
            {
                return new global::LightSwitchApplication.CorreosDeAvisosItem(es);
            }
            private static void __CorreosDeAvisosItem_Created(global::LightSwitchApplication.CorreosDeAvisosItem e)
            {
                e.CorreosDeAvisosItem_Created();
            }
            private static bool __CorreosDeAvisosItem_AllowSaveWithErrors(global::LightSwitchApplication.CorreosDeAvisosItem e)
            {
                bool result = false;
                e.CorreosDeAvisosItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, int> id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string> Nombre
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.Nombre) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string> Email
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.Email) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string> Descripcion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.Descripcion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::System.Nullable<bool>> RolPrivado
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties.RolPrivado) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int id { get; }
                new string Nombre { get; set; }
                new string Email { get; set; }
                new string Descripcion { get; set; }
                new global::System.Nullable<bool> RolPrivado { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, int>.Entry
                    id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, int>.Entry(
                        "id",
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._id_Stub,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._id_ComputeIsReadOnly,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._id_Validate,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._id_OnValueChanged);
                private static void _id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d, object sf)
                {
                    c(d, ref d._id, sf);
                }
                private static bool _id_ComputeIsReadOnly(global::LightSwitchApplication.CorreosDeAvisosItem e)
                {
                    bool result = false;
                    e.id_IsReadOnly(ref result);
                    return result;
                }
                private static void _id_Validate(global::LightSwitchApplication.CorreosDeAvisosItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.id_Validate(r);
                }
                private static int _id_GetImplementationValue(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d)
                {
                    return d.ImplementationEntity.id;
                }
                private static void _id_OnValueChanged(global::LightSwitchApplication.CorreosDeAvisosItem e)
                {
                    e.id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Entry
                    Nombre = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Entry(
                        "Nombre",
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Nombre_Stub,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Nombre_ComputeIsReadOnly,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Nombre_Validate,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Nombre_GetImplementationValue,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Nombre_SetImplementationValue,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Nombre_OnValueChanged);
                private static void _Nombre_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Nombre, sf);
                }
                private static bool _Nombre_ComputeIsReadOnly(global::LightSwitchApplication.CorreosDeAvisosItem e)
                {
                    bool result = false;
                    e.Nombre_IsReadOnly(ref result);
                    return result;
                }
                private static void _Nombre_Validate(global::LightSwitchApplication.CorreosDeAvisosItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Nombre_Validate(r);
                }
                private static string _Nombre_GetImplementationValue(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Nombre;
                }
                private static void _Nombre_SetImplementationValue(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Nombre = v;
                }
                private static void _Nombre_OnValueChanged(global::LightSwitchApplication.CorreosDeAvisosItem e)
                {
                    e.Nombre_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Entry
                    Email = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Entry(
                        "Email",
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Email_Stub,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Email_ComputeIsReadOnly,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Email_Validate,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Email_GetImplementationValue,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Email_SetImplementationValue,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Email_OnValueChanged);
                private static void _Email_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Email, sf);
                }
                private static bool _Email_ComputeIsReadOnly(global::LightSwitchApplication.CorreosDeAvisosItem e)
                {
                    bool result = false;
                    e.Email_IsReadOnly(ref result);
                    return result;
                }
                private static void _Email_Validate(global::LightSwitchApplication.CorreosDeAvisosItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Email_Validate(r);
                }
                private static string _Email_GetImplementationValue(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Email;
                }
                private static void _Email_SetImplementationValue(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Email = v;
                }
                private static void _Email_OnValueChanged(global::LightSwitchApplication.CorreosDeAvisosItem e)
                {
                    e.Email_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Entry
                    Descripcion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Entry(
                        "Descripcion",
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Descripcion_Stub,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Descripcion_ComputeIsReadOnly,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Descripcion_Validate,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Descripcion_GetImplementationValue,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Descripcion_SetImplementationValue,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._Descripcion_OnValueChanged);
                private static void _Descripcion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Descripcion, sf);
                }
                private static bool _Descripcion_ComputeIsReadOnly(global::LightSwitchApplication.CorreosDeAvisosItem e)
                {
                    bool result = false;
                    e.Descripcion_IsReadOnly(ref result);
                    return result;
                }
                private static void _Descripcion_Validate(global::LightSwitchApplication.CorreosDeAvisosItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Descripcion_Validate(r);
                }
                private static string _Descripcion_GetImplementationValue(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Descripcion;
                }
                private static void _Descripcion_SetImplementationValue(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Descripcion = v;
                }
                private static void _Descripcion_OnValueChanged(global::LightSwitchApplication.CorreosDeAvisosItem e)
                {
                    e.Descripcion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::System.Nullable<bool>>.Entry
                    RolPrivado = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "RolPrivado",
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._RolPrivado_Stub,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._RolPrivado_ComputeIsReadOnly,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._RolPrivado_Validate,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._RolPrivado_GetImplementationValue,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._RolPrivado_SetImplementationValue,
                        global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass.PropertySetProperties._RolPrivado_OnValueChanged);
                private static void _RolPrivado_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RolPrivado, sf);
                }
                private static bool _RolPrivado_ComputeIsReadOnly(global::LightSwitchApplication.CorreosDeAvisosItem e)
                {
                    bool result = false;
                    e.RolPrivado_IsReadOnly(ref result);
                    return result;
                }
                private static void _RolPrivado_Validate(global::LightSwitchApplication.CorreosDeAvisosItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RolPrivado_Validate(r);
                }
                private static global::System.Nullable<bool> _RolPrivado_GetImplementationValue(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RolPrivado;
                }
                private static void _RolPrivado_SetImplementationValue(global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.RolPrivado = v;
                }
                private static void _RolPrivado_OnValueChanged(global::LightSwitchApplication.CorreosDeAvisosItem e)
                {
                    e.RolPrivado_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, int>.Data _id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Data _Nombre;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Data _Email;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, string>.Data _Descripcion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CorreosDeAvisosItem, global::LightSwitchApplication.CorreosDeAvisosItem.DetailsClass, global::System.Nullable<bool>>.Data _RolPrivado;
            
        }
    
        #endregion
    }
    
    #endregion
}
