

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class dtpropertiesItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad dtpropertiesItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dtpropertiesItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dtpropertiesItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.dtpropertiesItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.dtpropertiesItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void dtpropertiesItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void dtpropertiesItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int id
        {
            get
            {
                return global::LightSwitchApplication.dtpropertiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> objectid
        {
            get
            {
                return global::LightSwitchApplication.dtpropertiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.objectid);
            }
            set
            {
                global::LightSwitchApplication.dtpropertiesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.objectid, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void objectid_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void objectid_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void objectid_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string c_property
        {
            get
            {
                return global::LightSwitchApplication.dtpropertiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.c_property);
            }
            set
            {
                global::LightSwitchApplication.dtpropertiesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.c_property, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_property_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_property_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_property_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string value
        {
            get
            {
                return global::LightSwitchApplication.dtpropertiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.value);
            }
            set
            {
                global::LightSwitchApplication.dtpropertiesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.value, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void value_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void value_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void value_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string uvalue
        {
            get
            {
                return global::LightSwitchApplication.dtpropertiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.uvalue);
            }
            set
            {
                global::LightSwitchApplication.dtpropertiesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.uvalue, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void uvalue_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void uvalue_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void uvalue_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] lvalue
        {
            get
            {
                return global::LightSwitchApplication.dtpropertiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.lvalue);
            }
            set
            {
                global::LightSwitchApplication.dtpropertiesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.lvalue, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void lvalue_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void lvalue_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void lvalue_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int version
        {
            get
            {
                return global::LightSwitchApplication.dtpropertiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.version);
            }
            set
            {
                global::LightSwitchApplication.dtpropertiesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.version, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void version_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void version_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void version_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.dtpropertiesItem,
                global::LightSwitchApplication.dtpropertiesItem.DetailsClass,
                global::LightSwitchApplication.dtpropertiesItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass>.Entry
                __dtpropertiesItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.dtpropertiesItem.DetailsClass.__dtpropertiesItem_CreateNew,
                    global::LightSwitchApplication.dtpropertiesItem.DetailsClass.__dtpropertiesItem_Created,
                    global::LightSwitchApplication.dtpropertiesItem.DetailsClass.__dtpropertiesItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.dtpropertiesItem __dtpropertiesItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.dtpropertiesItem> es)
            {
                return new global::LightSwitchApplication.dtpropertiesItem(es);
            }
            private static void __dtpropertiesItem_Created(global::LightSwitchApplication.dtpropertiesItem e)
            {
                e.dtpropertiesItem_Created();
            }
            private static bool __dtpropertiesItem_AllowSaveWithErrors(global::LightSwitchApplication.dtpropertiesItem e)
            {
                bool result = false;
                e.dtpropertiesItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int> id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::System.Nullable<int>> objectid
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.objectid) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string> c_property
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.c_property) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string> value
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.value) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string> uvalue
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.uvalue) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, byte[]> lvalue
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.lvalue) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int> version
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties.version) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int id { get; }
                new global::System.Nullable<int> objectid { get; set; }
                new string c_property { get; set; }
                new string value { get; set; }
                new string uvalue { get; set; }
                new byte[] lvalue { get; set; }
                new int version { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int>.Entry
                    id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int>.Entry(
                        "id",
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._id_Stub,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._id_ComputeIsReadOnly,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._id_Validate,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._id_OnValueChanged);
                private static void _id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._id, sf);
                }
                private static bool _id_ComputeIsReadOnly(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    bool result = false;
                    e.id_IsReadOnly(ref result);
                    return result;
                }
                private static void _id_Validate(global::LightSwitchApplication.dtpropertiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.id_Validate(r);
                }
                private static int _id_GetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.id;
                }
                private static void _id_OnValueChanged(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    e.id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::System.Nullable<int>>.Entry
                    objectid = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::System.Nullable<int>>.Entry(
                        "objectid",
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._objectid_Stub,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._objectid_ComputeIsReadOnly,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._objectid_Validate,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._objectid_GetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._objectid_SetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._objectid_OnValueChanged);
                private static void _objectid_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._objectid, sf);
                }
                private static bool _objectid_ComputeIsReadOnly(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    bool result = false;
                    e.objectid_IsReadOnly(ref result);
                    return result;
                }
                private static void _objectid_Validate(global::LightSwitchApplication.dtpropertiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.objectid_Validate(r);
                }
                private static global::System.Nullable<int> _objectid_GetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.objectid;
                }
                private static void _objectid_SetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.objectid = v;
                }
                private static void _objectid_OnValueChanged(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    e.objectid_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Entry
                    c_property = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Entry(
                        "c_property",
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._c_property_Stub,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._c_property_ComputeIsReadOnly,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._c_property_Validate,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._c_property_GetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._c_property_SetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._c_property_OnValueChanged);
                private static void _c_property_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._c_property, sf);
                }
                private static bool _c_property_ComputeIsReadOnly(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    bool result = false;
                    e.c_property_IsReadOnly(ref result);
                    return result;
                }
                private static void _c_property_Validate(global::LightSwitchApplication.dtpropertiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.c_property_Validate(r);
                }
                private static string _c_property_GetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.c_property;
                }
                private static void _c_property_SetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.c_property = v;
                }
                private static void _c_property_OnValueChanged(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    e.c_property_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Entry
                    value = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Entry(
                        "value",
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._value_Stub,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._value_ComputeIsReadOnly,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._value_Validate,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._value_GetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._value_SetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._value_OnValueChanged);
                private static void _value_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._value, sf);
                }
                private static bool _value_ComputeIsReadOnly(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    bool result = false;
                    e.value_IsReadOnly(ref result);
                    return result;
                }
                private static void _value_Validate(global::LightSwitchApplication.dtpropertiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.value_Validate(r);
                }
                private static string _value_GetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.value;
                }
                private static void _value_SetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.value = v;
                }
                private static void _value_OnValueChanged(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    e.value_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Entry
                    uvalue = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Entry(
                        "uvalue",
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._uvalue_Stub,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._uvalue_ComputeIsReadOnly,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._uvalue_Validate,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._uvalue_GetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._uvalue_SetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._uvalue_OnValueChanged);
                private static void _uvalue_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._uvalue, sf);
                }
                private static bool _uvalue_ComputeIsReadOnly(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    bool result = false;
                    e.uvalue_IsReadOnly(ref result);
                    return result;
                }
                private static void _uvalue_Validate(global::LightSwitchApplication.dtpropertiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.uvalue_Validate(r);
                }
                private static string _uvalue_GetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.uvalue;
                }
                private static void _uvalue_SetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.uvalue = v;
                }
                private static void _uvalue_OnValueChanged(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    e.uvalue_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, byte[]>.Entry
                    lvalue = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, byte[]>.Entry(
                        "lvalue",
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._lvalue_Stub,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._lvalue_ComputeIsReadOnly,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._lvalue_Validate,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._lvalue_GetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._lvalue_SetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._lvalue_OnValueChanged);
                private static void _lvalue_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._lvalue, sf);
                }
                private static bool _lvalue_ComputeIsReadOnly(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    bool result = false;
                    e.lvalue_IsReadOnly(ref result);
                    return result;
                }
                private static void _lvalue_Validate(global::LightSwitchApplication.dtpropertiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.lvalue_Validate(r);
                }
                private static byte[] _lvalue_GetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.lvalue;
                }
                private static void _lvalue_SetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.lvalue = v;
                }
                private static void _lvalue_OnValueChanged(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    e.lvalue_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int>.Entry
                    version = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int>.Entry(
                        "version",
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._version_Stub,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._version_ComputeIsReadOnly,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._version_Validate,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._version_GetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._version_SetImplementationValue,
                        global::LightSwitchApplication.dtpropertiesItem.DetailsClass.PropertySetProperties._version_OnValueChanged);
                private static void _version_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._version, sf);
                }
                private static bool _version_ComputeIsReadOnly(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    bool result = false;
                    e.version_IsReadOnly(ref result);
                    return result;
                }
                private static void _version_Validate(global::LightSwitchApplication.dtpropertiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.version_Validate(r);
                }
                private static int _version_GetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.version;
                }
                private static void _version_SetImplementationValue(global::LightSwitchApplication.dtpropertiesItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.version = v;
                }
                private static void _version_OnValueChanged(global::LightSwitchApplication.dtpropertiesItem e)
                {
                    e.version_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int>.Data _id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, global::System.Nullable<int>>.Data _objectid;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Data _c_property;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Data _value;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, string>.Data _uvalue;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, byte[]>.Data _lvalue;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.dtpropertiesItem, global::LightSwitchApplication.dtpropertiesItem.DetailsClass, int>.Data _version;
            
        }
    
        #endregion
    }
    
    #endregion
}
