

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No hay ninguna descripción modelada
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Solicitud_Detalle_HorasExtrasItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Inicializa una nueva instancia de la entidad Solicitud_Detalle_HorasExtrasItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Solicitud_Detalle_HorasExtrasItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Solicitud_Detalle_HorasExtrasItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Solicitud_Detalle_HorasExtrasItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Solicitud_Detalle_HorasExtrasItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id_HorasExtras
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Id_HorasExtras);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_HorasExtras_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_HorasExtras_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_HorasExtras_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime FechaRealizacion
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.FechaRealizacion);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.FechaRealizacion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FechaRealizacion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FechaRealizacion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FechaRealizacion_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double HorasAutorizadas
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.HorasAutorizadas);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.HorasAutorizadas, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HorasAutorizadas_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HorasAutorizadas_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HorasAutorizadas_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> HorasTrabajadas
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.HorasTrabajadas);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.HorasTrabajadas, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HorasTrabajadas_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HorasTrabajadas_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void HorasTrabajadas_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> Colacion
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Colacion);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Colacion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Colacion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Colacion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Colacion_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> Taxi
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Taxi);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Taxi, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Taxi_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Taxi_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Taxi_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Solicitud_HeaderItem Solicitud_HeaderItem
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Solicitud_HeaderItem);
            }
            set
            {
                global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.SetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Solicitud_HeaderItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Solicitud_HeaderItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Solicitud_HeaderItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Solicitud_HeaderItem_Changed();

        /// <summary>
        /// No hay ninguna descripción modelada
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem> Solicitud_Estados_HorasExtras
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.GetValue(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Solicitud_Estados_HorasExtras);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem> Solicitud_Estados_HorasExtrasQuery
        {
            get
            {
                return global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Solicitud_Estados_HorasExtras);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem,
                global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass,
                global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Id_HorasExtras;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass>.Entry
                __Solicitud_Detalle_HorasExtrasItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.__Solicitud_Detalle_HorasExtrasItem_CreateNew,
                    global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.__Solicitud_Detalle_HorasExtrasItem_Created,
                    global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.__Solicitud_Detalle_HorasExtrasItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem __Solicitud_Detalle_HorasExtrasItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem> es)
            {
                return new global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem(es);
            }
            private static void __Solicitud_Detalle_HorasExtrasItem_Created(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
            {
                e.Solicitud_Detalle_HorasExtrasItem_Created();
            }
            private static bool __Solicitud_Detalle_HorasExtrasItem_AllowSaveWithErrors(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
            {
                bool result = false;
                e.Solicitud_Detalle_HorasExtrasItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, int> Id_HorasExtras
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Id_HorasExtras) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.DateTime> FechaRealizacion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.FechaRealizacion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, double> HorasAutorizadas
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.HorasAutorizadas) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<double>> HorasTrabajadas
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.HorasTrabajadas) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>> Colacion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Colacion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>> Taxi
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Taxi) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_HeaderItem> Solicitud_HeaderItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Solicitud_HeaderItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_HeaderItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem> Solicitud_Estados_HorasExtras
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Solicitud_Estados_HorasExtras) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id_HorasExtras { get; }
                new global::System.DateTime FechaRealizacion { get; set; }
                new double HorasAutorizadas { get; set; }
                new global::System.Nullable<double> HorasTrabajadas { get; set; }
                new global::System.Nullable<bool> Colacion { get; set; }
                new global::System.Nullable<bool> Taxi { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Solicitud_HeaderItem { get; set; }
                new global::System.Collections.IEnumerable Solicitud_Estados_HorasExtras { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, int>.Entry
                    Id_HorasExtras = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, int>.Entry(
                        "Id_HorasExtras",
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Id_HorasExtras_Stub,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Id_HorasExtras_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Id_HorasExtras_Validate,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Id_HorasExtras_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Id_HorasExtras_OnValueChanged);
                private static void _Id_HorasExtras_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id_HorasExtras, sf);
                }
                private static bool _Id_HorasExtras_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    bool result = false;
                    e.Id_HorasExtras_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_HorasExtras_Validate(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_HorasExtras_Validate(r);
                }
                private static int _Id_HorasExtras_GetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id_HorasExtras;
                }
                private static void _Id_HorasExtras_OnValueChanged(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    e.Id_HorasExtras_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.DateTime>.Entry
                    FechaRealizacion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.DateTime>.Entry(
                        "FechaRealizacion",
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._FechaRealizacion_Stub,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._FechaRealizacion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._FechaRealizacion_Validate,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._FechaRealizacion_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._FechaRealizacion_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._FechaRealizacion_OnValueChanged);
                private static void _FechaRealizacion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, object sf)
                {
                    c(d, ref d._FechaRealizacion, sf);
                }
                private static bool _FechaRealizacion_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    bool result = false;
                    e.FechaRealizacion_IsReadOnly(ref result);
                    return result;
                }
                private static void _FechaRealizacion_Validate(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FechaRealizacion_Validate(r);
                }
                private static global::System.DateTime _FechaRealizacion_GetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    return d.ImplementationEntity.FechaRealizacion;
                }
                private static void _FechaRealizacion_SetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.FechaRealizacion = global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.TruncateDate(v);
                }
                private static void _FechaRealizacion_OnValueChanged(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    e.FechaRealizacion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, double>.Entry
                    HorasAutorizadas = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, double>.Entry(
                        "HorasAutorizadas",
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasAutorizadas_Stub,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasAutorizadas_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasAutorizadas_Validate,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasAutorizadas_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasAutorizadas_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasAutorizadas_OnValueChanged);
                private static void _HorasAutorizadas_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, double>.Data> c, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, object sf)
                {
                    c(d, ref d._HorasAutorizadas, sf);
                }
                private static bool _HorasAutorizadas_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    bool result = false;
                    e.HorasAutorizadas_IsReadOnly(ref result);
                    return result;
                }
                private static void _HorasAutorizadas_Validate(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.HorasAutorizadas_Validate(r);
                }
                private static double _HorasAutorizadas_GetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    return d.ImplementationEntity.HorasAutorizadas;
                }
                private static void _HorasAutorizadas_SetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, double v)
                {
                    d.ImplementationEntity.HorasAutorizadas = v;
                }
                private static void _HorasAutorizadas_OnValueChanged(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    e.HorasAutorizadas_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<double>>.Entry
                    HorasTrabajadas = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<double>>.Entry(
                        "HorasTrabajadas",
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasTrabajadas_Stub,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasTrabajadas_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasTrabajadas_Validate,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasTrabajadas_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasTrabajadas_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._HorasTrabajadas_OnValueChanged);
                private static void _HorasTrabajadas_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, object sf)
                {
                    c(d, ref d._HorasTrabajadas, sf);
                }
                private static bool _HorasTrabajadas_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    bool result = false;
                    e.HorasTrabajadas_IsReadOnly(ref result);
                    return result;
                }
                private static void _HorasTrabajadas_Validate(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.HorasTrabajadas_Validate(r);
                }
                private static global::System.Nullable<double> _HorasTrabajadas_GetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    return d.ImplementationEntity.HorasTrabajadas;
                }
                private static void _HorasTrabajadas_SetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.HorasTrabajadas = v;
                }
                private static void _HorasTrabajadas_OnValueChanged(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    e.HorasTrabajadas_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>>.Entry
                    Colacion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "Colacion",
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Colacion_Stub,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Colacion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Colacion_Validate,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Colacion_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Colacion_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Colacion_OnValueChanged);
                private static void _Colacion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Colacion, sf);
                }
                private static bool _Colacion_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    bool result = false;
                    e.Colacion_IsReadOnly(ref result);
                    return result;
                }
                private static void _Colacion_Validate(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Colacion_Validate(r);
                }
                private static global::System.Nullable<bool> _Colacion_GetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Colacion;
                }
                private static void _Colacion_SetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.Colacion = v;
                }
                private static void _Colacion_OnValueChanged(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    e.Colacion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>>.Entry
                    Taxi = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "Taxi",
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Taxi_Stub,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Taxi_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Taxi_Validate,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Taxi_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Taxi_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Taxi_OnValueChanged);
                private static void _Taxi_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Taxi, sf);
                }
                private static bool _Taxi_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    bool result = false;
                    e.Taxi_IsReadOnly(ref result);
                    return result;
                }
                private static void _Taxi_Validate(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Taxi_Validate(r);
                }
                private static global::System.Nullable<bool> _Taxi_GetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Taxi;
                }
                private static void _Taxi_SetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.Taxi = v;
                }
                private static void _Taxi_OnValueChanged(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    e.Taxi_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_HeaderItem>.Entry
                    Solicitud_HeaderItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_HeaderItem>.Entry(
                        "Solicitud_HeaderItem",
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_HeaderItem_Stub,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_HeaderItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_HeaderItem_Validate,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_HeaderItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_HeaderItem_GetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_HeaderItem_SetImplementationValue,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_HeaderItem_Refresh,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_HeaderItem_OnValueChanged);
                private static void _Solicitud_HeaderItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_HeaderItem>.Data> c, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Solicitud_HeaderItem, sf);
                }
                private static bool _Solicitud_HeaderItem_ComputeIsReadOnly(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    bool result = false;
                    e.Solicitud_HeaderItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _Solicitud_HeaderItem_Validate(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Solicitud_HeaderItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Solicitud_HeaderItem_GetCoreImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Solicitud_HeaderItem;
                }
                private static global::LightSwitchApplication.Solicitud_HeaderItem _Solicitud_HeaderItem_GetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Solicitud_HeaderItem, global::LightSwitchApplication.Solicitud_HeaderItem.DetailsClass>(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Solicitud_HeaderItem, ref d._Solicitud_HeaderItem);
                }
                private static void _Solicitud_HeaderItem_SetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, global::LightSwitchApplication.Solicitud_HeaderItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Solicitud_HeaderItem, ref d._Solicitud_HeaderItem, (i, ev) => i.Solicitud_HeaderItem = ev, v);
                }
                private static void _Solicitud_HeaderItem_Refresh(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Solicitud_HeaderItem, ref d._Solicitud_HeaderItem);
                }
                private static void _Solicitud_HeaderItem_OnValueChanged(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem e)
                {
                    e.Solicitud_HeaderItem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem>.Entry
                    Solicitud_Estados_HorasExtras = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem>.Entry(
                        "Solicitud_Estados_HorasExtras",
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_Estados_HorasExtras_Stub,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_Estados_HorasExtras_GetReferencedEntities,
                        global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties._Solicitud_Estados_HorasExtras_GetEntityCollection);
                private static void _Solicitud_Estados_HorasExtras_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem>.Data> c, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Solicitud_Estados_HorasExtras, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem> _Solicitud_Estados_HorasExtras_GetReferencedEntities(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem.DetailsClass>(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass.PropertySetProperties.Solicitud_Estados_HorasExtras, ref d._Solicitud_Estados_HorasExtras);
                }
                private static global::System.Collections.IEnumerable _Solicitud_Estados_HorasExtras_GetEntityCollection(global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Solicitud_Estados_HorasExtras;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, int>.Data _Id_HorasExtras;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.DateTime>.Data _FechaRealizacion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, double>.Data _HorasAutorizadas;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<double>>.Data _HorasTrabajadas;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>>.Data _Colacion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::System.Nullable<bool>>.Data _Taxi;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_HeaderItem>.Data _Solicitud_HeaderItem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem, global::LightSwitchApplication.Solicitud_Detalle_HorasExtrasItem.DetailsClass, global::LightSwitchApplication.Solicitud_Estados_HorasExtrasItem>.Data _Solicitud_Estados_HorasExtras;
            
        }
    
        #endregion
    }
    
    #endregion
}
