//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    /// <summary>
    /// Defines the names of the application permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static class Permissions
    {
        /// <summary>
        /// Permite administrar la seguridad de la aplicación.
        /// </summary>
        public const string SecurityAdministration = global::Microsoft.LightSwitch.Security.ApplicationPermissions.SecurityAdministration;
        /// <summary>
        /// Permite el acceso a las pantallas de rol privado.
        /// </summary>
        public const string AdminRolPrivado = "LightSwitchApplication:AdminRolPrivado";
        /// <summary>
        /// Permite el acceso a las pantallas de rrhh
        /// </summary>
        public const string AdminRRHH = "LightSwitchApplication:AdminRRHH";
        /// <summary>
        /// Soy_Gustavo
        /// </summary>
        public const string Soy_Gustavo = "LightSwitchApplication:Soy_Gustavo";
        /// <summary>
        /// Soy_Salome
        /// </summary>
        public const string Soy_Salome = "LightSwitchApplication:Soy_Salome";
        /// <summary>
        /// Soy_Moises
        /// </summary>
        public const string Soy_Moises = "LightSwitchApplication:Soy_Moises";
        /// <summary>
        /// Soy_Valeria
        /// </summary>
        public const string Soy_Valeria = "LightSwitchApplication:Soy_Valeria";
        /// <summary>
        /// Soy_Cesar
        /// </summary>
        public const string Soy_Cesar = "LightSwitchApplication:Soy_Cesar";

        /// <summary>
        /// Obtiene todos los permisos definidos para la aplicación. esto incluye los permisos del sistema y definidos por el usuario.
        /// </summary>
        public static global::System.Collections.ObjectModel.ReadOnlyCollection<string> AllPermissions { get { return global::Microsoft.LightSwitch.Security.ApplicationPermissions.AllPermissions; } }
    }
}
